import { Inter, Lato } from "next/font/google";
import "./globals.css";
import ClientLayout from "./(layout)/ClientLayout";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable} 
          ${lato.variable}
        `}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
